### ISSUE TITLE
Incorrect liftdrag when we reverse.

### ISSUE THREAD

**Issue by arjo129** [osrf/lrauv#55]
![incorrect_liftdragwhenreverse](https://user-images.githubusercontent.com/542272/139389461-31fd40f2-0cbb-4b3b-b791-368ce8bd3e1f.gif)
In the above example hydrodynamics is disabled. but for some reason we get a wierd cartwheel if the vehicle is moving in reverse. The deep blue arrow indicates that this is due to the liftdrag from the Rudder.

**Comment by tfoote** [comment]
This is not horribly unreasonable behavior if there's basically any instability in the lateral control. The fins are specifically at the back of the vehicle because that's the stable direction of travel. Once you get going faster than a certain speed and have a lateral disturbance causing the fins to catch the water going past from the side instead of the edge they will immediately start initiate a spin and as the spin accelerates get more leverage until they're perpendicular to the flow. 

I think that this has even more credence as if you watch after it completes the 180 rotation, so it's facing forward velocity, you can see the fins force increasing in a way to stop the inertia of the spin and correct the 

I'm trying to come up with a good example of it. Such as a hammerhead stall recovery. Maybe a clearer example is when a model rocket reaches the top and then starts falling backwards. At some point the passive fins cause it to flip around. That's this motion.

There's a speed at which the vehicle will be basically unstable and flip around uncontrollably like this.

**Comment by braanan** [comment]
We only use reverse for short bursts to back off objects (like a line dock) with all control surfaces held constant. The LRAUV controller is not set up to handle control in reverse.

**Comment by arjo129** [comment]
Ooh OK! Thanks for the clear explanation @tfoote! @braanan  thanks for letting me know about this, it kind of explains some of the other weird behavior I see when reversing.  Closing this issue as its a non-issue.
